package CustomUI;

public enum TagState {
    CREATING,
    CREATION_DONE,
    MOVING,
    ATTEMPT_TO_MOVE,
    RESIZING_RIGHT_BUTTOM,
    RESIZING_LEFT_UP,
    ATTEMPT_TO_RESIZE_RIGHT_BUTTOM,
    ATTEMPT_TO_RESIZE_LEFT_UP,
    SELECTED
}
